### ISSUE TITLE
fix: `render.registrycredentials.listRegistryCredentials` returns 402

### ISSUE THREAD

**Issue by VladimirCreator** [cloudy-sky-software/pulumi-render#363]
```
    error: http request failed (status: 402 Payment Required): {"message":"Payment information is required to complete this request. To add a card, visit https://dashboard.render.com/billing"}
```
`render.registrycredentials.listRegistryCredentials()` results the error

The problem is that if I just make a request myself through Insomnia, such an error does not occur :/

Maybe I misunderstood something. I use this route: `https://api.render.com/v1/registrycredentials`

**Comment by praneetloke** [comment]
@VladimirCreator that's strange. I just ran that function and didn't get any errors. I don't have any registries in my account though. Are you sure the API key that you are using is tied to an account that has billing enabled?

**Comment by VladimirCreator** [comment]
@praneetloke seems like I’m doing something wrong 🙂 I’ll write you in a while

**Comment by VladimirCreator** [comment]
@praneetloke yeah, I actually did not enabled billing and was trying to use paid plan.
